(rocq.extraction
 (prelude Extract)
 (extracted_modules
  Ascii
  Ast
  Attributes
  BinInt
  BinNat
  BinNums
  BinPos
  Bool0
  Datatypes
  Decimal
  DecimalString
  Document
  Fixtures
  FMapAVL
  FMapList
  Generate
  Hexadecimal
  Html
  Inline
  InlineLocated
  InlineScan
  InlineTable
  InlineView
  Int
  Line
  List0
  ListDef
  ListUniformity
  Marker
  MSetAVL
  MSetInterface
  Nat0
  Number
  OrderedList
  OrderedType
  OrderedTypeEx
  Orders
  OrdersEx
  OrdersFacts
  OrdersTac
  PeanoNat
  PosDef
  Profile
  Render
  Specif
  Step
  String0
  Strings
  Uniformity)
 (theories DjotV DjotVDev Stdlib))

(library
 (name djot)
 (modules :standard \ Fixtures Generate)
 (flags
  (:standard -w -a)))

(library
 (name djot_fixtures)
 (modules Fixtures Generate)
 (libraries djot)
 (flags
  (:standard -w -a -open Djot)))
